# Generated by Django 4.1.3 on 2023-02-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0002_alter_employeemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={},
        ),
    ]
